/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
interface __BaseEnv_Env {
  AI: Ai;
  BROWSER: import("agents/browser").QuickActionBinding;
  BAI_BASE_URL: string;
  BAI_API_KEY: string;
  BAI_MODEL?: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET_TOKEN: string;
  TELEGRAM_BOT_USERNAME: string;
  ChatIngressAgent: DurableObjectNamespace<
    import("./src/index").ChatIngressAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ChatIngressAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "TELEGRAM_BOT_TOKEN"
      | "TELEGRAM_WEBHOOK_SECRET_TOKEN"
      | "TELEGRAM_BOT_USERNAME"
    >
  > {}
}
