/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f4a5145dc046cca77a5b0bc2fbce708e)
interface __BaseEnv_Env {
  AI: Ai;
  PiAgent: DurableObjectNamespace<import("./src/server").PiAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PiAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
